### ISSUE TITLE
video_capture gba demo not displaying correctly

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#104]
[video_capture.zip](https://github.com/skylersaleh/SkyEmu/files/9637730/video_capture.zip)

**Comment by skylersaleh** [comment]
Ladystarbreeze has a good overview of this rom here. Looks like it is testing an edge case of video capture DMA. 

https://github.com/mgba-emu/mgba/issues/2017

**Comment by skylersaleh** [comment]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/7118296/192109546-d32c5cbe-14c9-48dc-8dc5-b195018a59e1.png">

I have a fix in dev now, but I am looking for some more confirmation about the behavior of the last scanline (whether it should be white or black), as I have to implement slightly different behavior to the documented behavior to get it to appear white.

**Comment by skylersaleh** [comment]
Closing this issue as I was able to confirm with Lady Starbreeze that the correct behavior yields a white scanline.

**Comment by sczther** [comment]
For me in SkyEmu v2 the last scanline is black. In NBA v1.6 it is white. So what is the right behaviour?
