### ISSUE TITLE
[Feature Request] Remove black bars maybe ignore aspect ratio option

### ISSUE THREAD

**Issue by mrdeathjr28** [skylersaleh/SkyEmu#112]
Hi

Maybe can add some option for remove black bars like ignore aspect ratio option

thanks

**Comment by skylersaleh** [comment]
Hi, 

I added this feature to the dev branch. You can get it here: https://github.com/skylersaleh/SkyEmu/pull/40

It can be activated by clicking the circled checkbox.

<img width="1463" alt="Screen Shot 2022-10-17 at 5 43 25 AM" src="https://user-images.githubusercontent.com/7118296/196180303-b9509b34-8905-495e-af2d-ce96a5ac8e16.png">

Thanks,

-Sky
