### ISSUE TITLE
can't open ROMs with special characters

### ISSUE THREAD

**Issue by Kuro6804** [skylersaleh/SkyEmu#115]
Tried opening a Pokémon ROM and it wouldn't open until I replaced the é with an e.
I also use en and em dashes and ː in my file names to replace colons which won't work either.

**Comment by skylersaleh** [comment]
Thanks for reporting this, could you let me know whether you are seeing this on the Windows, Mac, Linux or Web builds?

**Comment by Kuro6804** [comment]
I'm using the 2.0 Windows build.
Web build seems to work just fine.

**Comment by skylersaleh** [comment]
Hi Kuro, 

This should be fixed by the new UTF-8 support I just added in: https://github.com/skylersaleh/SkyEmu/pull/143

Let me know if it doesn't work for you. 

-Sky
