### ISSUE TITLE
[Feature Request] Full screen without menu/emulation/volume control bar

### ISSUE THREAD

**Issue by hbCyber** [skylersaleh/SkyEmu#123]
I tried to look for documentation, but couldn't find anything that describes how to hide the menu/emulation/volume control bar at the top. There should be a way to allow the game to take up 100% of the screen without any controls visible. 

Ideally, there should be an assignable key that toggles the top bar's visibility on/off.

**Comment by skylersaleh** [comment]
This is implemented now in https://github.com/skylersaleh/SkyEmu/pull/143
