### ISSUE TITLE
Android port version?

### ISSUE THREAD

**Issue by DavidAriyan** [skylersaleh/SkyEmu#135]
I know there's already a web version, but i prefer for this multiple Gameboy emulator have a stand alone app version for android. And play games fully offline. The osc is really bad too.
I really like your idea with that emu and the app icon looks cute.
Please consider porting this to android.

**Comment by skylersaleh** [comment]
There is now an android native version with automatic Android builds here: https://github.com/skylersaleh/SkyEmu/pull/143

This is still very early, but playable.

**Comment by DavidAriyan** [comment]
Wow. Superb. This is what I need. All gb system emulator in one app. Thank
you so much for this.
You doing great. I hope I could help the development in any way that i can
do. Like making a unique on screen control for the android version.
I'm gonna try this right now.
Good job.

Pada tanggal Sab, 3 Des 2022 15.14, Sky ***@***.***> menulis:

**Comment by DavidAriyan** [comment]
I noticed it's doesn't use android UI. Would be nice if it use it. And probably a default folder set (in any directory user want) to scan the games.
But this still early. So I hope you could implement the android ui. Like any emus.
