### ISSUE TITLE
Can't open a game with Chinese name

### ISSUE THREAD

**Issue by kongmao45678** [skylersaleh/SkyEmu#139]
Can't open a game containing Chinese names, can it allow the program to support the ROM of the Chinese name

**Comment by nenge123** [comment]
概率很低,因为它的界面就是ascii码,支不支持UTF8不知道,就算支持也需要字体,

唯一希望作者增加JS接口方法,
可以通过JS加载游戏
通过JS检测游戏状态.
伪造一些自定义菜单选项,实现显示中文.

**Comment by skylersaleh** [comment]
Hi Kongmao, 

This should be fixed by the new UTF-8 support I just added in: https://github.com/skylersaleh/SkyEmu/pull/143

Let me know if it doesn't work for you.

-Sky
