### ISSUE TITLE
Lunix build not funtioning well

### ISSUE THREAD

**Issue by Jblades06lit** [skylersaleh/SkyEmu#142]
I am using a steam deck desktop to test this but it shouldn't be that much different from another os running this. 

With v1 of skyemu the app launchers right away with no issues in emulation performance than what is to be expected. However, with v2, launching the app from the desktop creates an unresponsive empty window that has to be killed from system monitor to close. While in the state is also is still using system resources. If launched with parameters from a game rom, then it loads imitatively but is a slow laggy mess hitting about 12fps not only when in game but also in the UI and pause menus.

Let me know if this is only an issue on my side, the reason I am even going through this is for the new color correction and scaling option because I dislike mGba and others options in that regard.

**Comment by skylersaleh** [comment]
I can't seem to reproduce this on my steam deck using out of the box settings. Is there anything that might be unique about your setup that you could tell me that might help me to reproduce the issue?

**Comment by skylersaleh** [comment]
Can not reproduce.
