### ISSUE TITLE
pure black

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#144]
for oled screens

**Comment by skylersaleh** [comment]
I just added an initial black theme to the V3 branch you can get at the link below. How does it look to you? 

https://github.com/skylersaleh/SkyEmu/pull/143

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/7118296/210122490-1a60124c-9999-4434-bb25-5f5de031e3f6.png">
