### ISSUE TITLE
reset

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#147]
![image154](https://user-images.githubusercontent.com/109885044/199873412-86e3c060-f50e-45f9-bbaf-335669b77e2d.png)
![image155](https://user-images.githubusercontent.com/109885044/199873419-cb9d3ae3-ea44-4903-bf0b-a99470c1c8ba.png)

Some people unintentionally skip the plot animation when they start the game

**Comment by skylersaleh** [comment]
I added a keybind for game reset to https://github.com/skylersaleh/SkyEmu/commit/8609065fd6adcaa8145672c116e790a29dd5da7e
