### ISSUE TITLE
[Feature Request] higan colour correction option

### ISSUE THREAD

**Issue by roomnoom** [skylersaleh/SkyEmu#148]
I really like how the colours look using higan option in nanoboyadvance, sorry in case this feature doesn't fit the spirit of this emulator
![Screenshot (2821)](https://user-images.githubusercontent.com/119942944/205919933-b3c52c31-e7f4-4f52-807f-cb5189c1743e.png)

**Comment by skylersaleh** [comment]
Thanks for filing the feature request. I'll put it on my stack of features to implement 👍

**Comment by skylersaleh** [comment]
I just added an option to this to the latest dev builds. 

<img width="312" alt="image" src="https://user-images.githubusercontent.com/7118296/213853316-ee0d1212-9bae-4e5c-a2ed-291b326586bc.png">

It will be part of the next release.
