### ISSUE TITLE
Cant open .sav files in SkyEmu

### ISSUE THREAD

**Issue by revvs9** [skylersaleh/SkyEmu#15]
Okay, so a while back i discovered SkyEmu when it couldn't import/export .sav files, now that it does support importing files i tried to test it, the bios loaded fine but I can't figure out how to open .sav files. Whenever i drag and drop the file, nothing happens. I quadruple checked that the name of the file was the same as the rom, but it still doesn't work. Please help 😃 (web version by the way)

**Comment by revvs9** [comment]
ok never mind i figured it out, first i drop the save file and then i drop the rom. i wish there was a pop up saying file successfully loaded or something. but, its fine now 😃

**Comment by skylersaleh** [comment]
Thanks revvs9 for filing this issue. I'll leave this open for me as a reminder to work on the UI to make this process more intuitive.

**Comment by Aversefun** [comment]
I know this is an old issue, but this is not working for me. Any ideas?
