### ISSUE TITLE
don't scan all files again when you want to change to another game

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#181]
3373 GBA files
13.08GB
For lowend hardware, it's not friendly

How i test it
GBA folder 1 file
open that game
move 3 new files to GBA folder
pause that game and open file browser
now GBA folder 4 files

or

enter empty GBA folder
copy files to that folder
back to SkyEmu
it scan all files again

if you want to make it rescan all files
you can exit that folder then enter that folder
or exit the app
it's not good for hardware life

**Comment by skylersaleh** [comment]
Caching of the FS queries has been incorporated in the dev branch.
