### ISSUE TITLE
file list swipe make it smoothly

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#182]
A low-end Android phone
This frontend File list let me swipe like a very slow GIF
A dying old computer
For a folder with 20 files, that's ok
but for three almost (impossible) complete Folders
That's disaster
Create 3 folders and uncompress three zip files
Nintendo - Game Boy
2038 zip files 227MB
Nintendo - Game Boy Color
1948 zip files 890MB
Nintendo - Game Boy Advance
3373 zip files 13GB
open a folder Nintendo - Game Boy Color
swipe list
my Android phone likely to told me it'll be dead
So that I won't try to open Nintendo - Game Boy Advance folder

You can reduce some useless duplicate info
and others I don't know how to optimize
It Just like Marat Fayzullin's emulators on Android (before Android 11)
make me uncomfortable I uninstalled his emulators
I don't like to wait a turtle run to goal

Go to parent directory
(Current Path) /sdcard/Games/Nintendo - Game Boy Advance

(zip) 
Game Boy Advance Video - Teenage 
Mutant Ninja Turtles - Le 
Demenagement (France)

no need to show 2 same file name, and extension for all files

another thing make me unhappy
I want to change to another game, I tested it scan files frequently
oh, don't do the same thing. It forgot it scanned files?

I tried Robert Broglia's emulators with huge files, more than 15GB.
It's ok. after scanning files It runs like a runner

and that's why i request for a state and save file path option

**Comment by skylersaleh** [comment]
Hi, I just implemented a better algorithm for the file browser. It provides >5x speedup on my machine for large file lists. 

Give it a shot at the download links on: https://github.com/skylersaleh/SkyEmu/pull/143
