### ISSUE TITLE
GUI adds multi language support

### ISSUE THREAD

**Issue by shooterspps** [skylersaleh/SkyEmu#189]
At present, I use source code translation to achieve Chinese display

" Load Game"	u8" 载入游戏"
"Up"	u8"上"
"Down"	u8"下"
"Left"	u8"左"
"Right"	u8"右"
"Start"	u8"开始"
"Select"	u8"选择"
"Fold Screen (NDS)"	u8"折叠屏幕 (NDS)"
"Tap Screen (NDS)"	u8"点击屏幕 (NDS)"
"Emulator "	u8"模拟器 "
"Capture State 0"	u8"即时存档 0"
"Restore State 0"	u8"即时读档 0"
"Capture State 1"	u8"即时存档 1"
"Restore State 1"	u8"即时读档 1"
"Capture State 2"	u8"即时存档 2"
"Restore State 2"	u8"即时读档 2"
"Capture State 3"	u8"即时存档 3"
"Restore State 3"	u8"即时读档 3"
"Analog Up/Down"	u8"摇杆 上/下"
"Analog Left/Right"	u8"摇杆 左/右"
"Analog L"	u8"扳机 L"
"Analog R"	u8"扳机 R"
"Display FPS: %2.1f\n"	u8"显示屏 FPS: %2.1f\n"
"Emulation FPS: %2.1f\n"	u8"模拟器 FPS: %2.1f\n"
" Audio"	u8" 音频"
"Left Audio Channel"	u8"音频左声道"
"Right Audio Channel"	u8"音频右声道"
"Channel 1 (Square)"	u8"声道 1 (方形)"
"Channel 2 (Square)"	u8"声道 2 (方形)"
"Channel 3 (Wave)"	u8"声道 3 (波形)"
"Channel 4 (Noise)"	u8"声道 4 (噪声)"
"Channel A (FIFO)"	u8"声道 A (FIFO)"
"Channel B (FIFO)"	u8"声道 B (FIFO)"
"Audio Ring (Samples Available: %d)"	u8"音频环绕 (可用采样: %d)"
"Audio Watchdog Triggered %d Times"	u8"音频定时触发 %d 时间"
" Build Info"	u8" 构建信息"
"Commit Hash:"	u8"哈希值提交:"
" Registers"	u8" 寄存器"
" Disassembly"	u8" 反汇编"
" Read/Write Memory Address"	u8" 读/写内存地址"
"address"	u8"地址"
"data (32 bit)"	u8"数据 (32 bit)"
"data (16 bit)"	u8"数据 (16 bit)"
"data (8 bit)"	u8"数据 (8 bit)"
"data (signed 32b)"	u8"数据 (写入 32b)"
"data (signed 16b)"	u8"数据 (写入 16b)"
"data (signed 8b)"	u8"数据 (写入 8b)"
" Memory"	u8" 内存"
" Emulator Stats"	u8" 模拟器统计"
"Show/Hide %s Panel\n"	u8"显示/隐藏 %s面板\n"
"Press new button "	u8"按下按键 "
"Move Axis "	u8"移动轴 "
"Not bound"	u8"不绑定"
"Hat %d %s"	u8"方向 %d %s"
"Analog %d %s"	u8"手柄轴 %d %s"
"Key %d"	u8"按键 %d"
"Analog %d (%0.2f)"	u8"手柄轴 %d (%0.2f)"
"Load ROM from file (.gb, .gbc, .gba, .zip)"	u8"从文件中载入 ROM (.gb, .gbc, .gba, .zip)"
"You can also drag & drop a ROM to load it"	u8"你也可以通过拖放载入一个 ROM"
"Load ROM(.gb, .gbc, .gba, .zip), save(.sav), or GBA bios (gba_bios.bin) from file"	u8"从文件中载入 ROM(.gb, .gbc, .gba, .zip), save(.sav), 或 GBA bios (gba_bios.bin)"
"You can also drag & drop a ROM/save file to load it"	u8"你也可以通过拖放载入一个 ROM/存档文件"
"Open ROM"	u8"打开 ROM"
" Load Recently Played Game"	u8" 载入最近玩过的游戏"
" Export Save"	u8" 导出存档"
"No recently played games"	u8"最近没有玩过游戏"
" Controllers"	u8" 控制器"
"No Controller"	u8"无控制器"
"Controller"	u8"控制器"
"No Controller"	u8"无控制器"
"Reset Default Controller Bindings"	u8"重置控制器默认绑定"
"Rumble Supported"	u8"支持震动"
"Rumble Not Supported"	u8"不支持震动"
" Save States"	u8" 即时存档"
"Save Slot %d"	u8"存档位置 %d"
"Capture"	u8"存档"
"Restore"	u8"读档"
"This save state came from an incompatible build. SkyEmu has attempted to recover it, but there may be issues"	u8"这个即时存档来自一个不兼容的构建. SkyEmu 已经尝试恢复, 但可能会有问题"
" Display Settings"	u8" 显示设置"
"Screen Shader"	u8"屏幕着色器"
"##Screen Shader"	u8"##屏幕着色器"
"Pixelate\0Bilinear\0LCD\0LCD & Subpixels\0Smooth Upscale (xBRZ)\0"	u8"像素化\0双线性\0LCD\0LCD & 子像素\0高级平滑过滤 (xBRZ)\0"
"Screen Rotation"	u8"屏幕旋转"
"##Screen Rotation"	u8"##屏幕旋转"
"0 degrees\00090 degrees\000180 degrees\000270 degrees\0"	u8"0°\00090°\000180°\000270°\0"
"Color Correction"	u8"颜色校正"
"##Color Correction"	u8"##颜色校正"
"Strength: %.2f"	u8"强度: %.2f"
"Screen Ghosting"	u8"屏幕残影"
"Force Integer Scaling"	u8"强制整数缩放"
"Stretch Screen to Fit"	u8"拉伸适应屏幕"
"Game Boy Color Palette"	u8"Game Boy Color 调色板"
"GB Palette %d"	u8"GB 调色板 %d"
"Reset Palette to Defaults"	u8"重置调色板默认值"
" Keybinds"	u8" 键盘快捷键"
"Reset Default Keybinds"	u8"重置键盘快捷键默认值"
" Advanced"	u8" 高级"
"Light Mode"	u8"浅色模式"
"Show Debug Tools"	u8"显示调试工具"
"Adjust volume"	u8"调节音量"
"Show/Hide Menu Panel"	u8"显示/隐藏菜单面板"
"Rewind at 8x speed"	u8"以8倍速度倒带"
"Rewind at 4x speed"	u8"以4倍速度倒带"
"Toggle pause/play.\n When paused, the rom selection screen will be shown."	u8"切换暂停/游玩.\n 暂停时, 屏幕显示选择 rom 菜单."
"Run at 2x Speed"	u8"以2倍速度快进"
"Run at the fastest speed possible"	u8"速度无限制快进"
"Screen"	u8"屏幕"
"##ClickRegion"	u8"##点击区域"
"LCD Shader Init"	u8"LCD 着色器初始化"
"Menu"	u8"菜单"
"Copy as.."	u8"复制.."
"Current"	u8"当前"
"Original"	u8"原始"
"Opacity"	u8"不透明度"
" Touch Control Settings"	u8" 触摸控制设置"
"Hide when inactive"	u8"不活动时隐藏"
" Dump Memory to File"	u8" 转储内存文件"
"Start Address"	u8"起始地址"
"Size"	u8"大小"
"Save Memory Dump"	u8"保存转储内存"
" Last Branch Locations"	u8" 最后分支位置"
"Opacity: %.2f"	u8"不透明度: %.2f"
"Step Instruction"	u8"步进指令"
"Disconnect Log"	u8"断开日志"
" Open File From Disk"	u8" 从磁盘打开文件"
"Exit File Browser"	u8"退出文件浏览"
"Go back to recently loaded games"	u8"返回最近载入的游戏"
"Go to parent directory"	u8"转到上级目录"
SDL_HAT_UP)dir="UP"	SDL_HAT_UP)dir=u8"上"
SDL_HAT_DOWN)dir="DOWN"	SDL_HAT_DOWN)dir=u8"下"
SDL_HAT_LEFT)dir="LEFT"	SDL_HAT_LEFT)dir=u8"左"
SDL_HAT_RIGHT)dir="RIGHT"	SDL_HAT_RIGHT)dir=u8"右"
"Reset Game"	u8"重置游戏"
"Turbo A"	u8"连发 A"
"Turbo B"	u8"连发 B"
"Turbo X"	u8"连发 X"
"Turbo Y"	u8"连发 Y"
"Turbo L"	u8"连发 L"
"Turbo R"	u8"连发 R"
"Solar Sensor+"	u8"太阳能传感器+"
"Solar Sensor-"	u8"太阳能传感器-"
"Theme"	u8"主题"
"Solar Sensor"	u8"太阳能传感器"
"Brightness: %.2f"	u8"亮度: %.2f"
"Dark\0Light\0Black\0"	u8"深色\0浅色\0黑色\0"
"Always Show Menu/Nav Bar"	u8"始终显示菜单/导航栏"

**Comment by skylersaleh** [comment]
Thanks! This translation is now included in https://github.com/skylersaleh/SkyEmu/pull/143

The program doesn't auto-detect the OS's language yet, so you will have to change your language manually to chinese in the settings.

**Comment by shooterspps** [comment]
> Thanks! This translation is now included in #143
> 
> The program doesn't auto-detect the OS's language yet, so you will have to change your language manually to chinese in the settings.

Thank you very much. The encoding of the following files must be transferred to UTF-8. Only after compilation can Chinese be displayed correctly, without random code

IconsForkAwesome.h
main.c
imgui_ widgets.cpp

**Comment by skylersaleh** [comment]
@shooterspps There are some new strings in the latest release. 

Can you help translate them? 

#ifdef SHOW_TRANSLATE_ME
    "Enable Turbo and Hold Button Modifiers", "TRANSLATE ME",
    "Scale", "TRANSLATE ME",
    "Scale: %.2f","TRANSLATE %.2f",
    "GBA Color Correction Type","TRANSLATE ME",
    ICON_FK_TEXT_HEIGHT " GUI",ICON_FK_TEXT_HEIGHT " TBD",
    "Full Screen","TBD",
    ICON_FK_CODE_FORK " Additional Search Paths",ICON_FK_CODE_FORK " TBD",
    "Save File/State Path","TBD",
    "BIOS/Firmware Path","TBD",
    "Create new save files in Save Path","TBD",
    ICON_FK_CROSSHAIRS " Located BIOS/Firmware Files",ICON_FK_CROSSHAIRS " TBD",
    "Force GB games to run in DMG mode","TBD",
    "Enable HTTP Control Server","TBD",
    "Server Port","TBD",
    "Toggle Full Screen","TBD",
#endif
