### ISSUE TITLE
Rotation 90, 270 disable Stretch to Fit

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#192]
![Screenshot_20230104-120519_Trebuchet](https://user-images.githubusercontent.com/109885044/210482733-fbb763b4-0df9-47bd-8343-35f45309ae73.png)
Stretch to Fit On
Rotate 0, 180

Rotate 90, 270
Stretch to Fit Off

**Comment by skylersaleh** [comment]
This is fixed in the latest dev builds.
