### ISSUE TITLE
more Games with special palettes

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#195]
Games with special palettes include:

    [Donkey Kong](https://en.m.wikipedia.org/wiki/Donkey_Kong_(Game_Boy))
    [Golf](https://en.m.wikipedia.org/wiki/Golf_(Game_Boy))
    [Kirby's Dream Land](https://en.m.wikipedia.org/wiki/Kirby%27s_Dream_Land)
    [Kirby's Dream Land 2](https://en.m.wikipedia.org/wiki/Kirby%27s_Dream_Land_2)
    [Kirby's Pinball Land](https://en.m.wikipedia.org/wiki/Kirby%27s_Pinball_Land)
    [Metroid II: Return of Samus](https://en.m.wikipedia.org/wiki/Metroid_II:_Return_of_Samus)
    [Pokémon Red and Blue](https://en.m.wikipedia.org/wiki/Pok%C3%A9mon_Red_and_Blue)
    [Pokémon Yellow](https://en.m.wikipedia.org/wiki/Pok%C3%A9mon_Yellow) (original Game Boy version)
    [Super Mario Land](https://en.m.wikipedia.org/wiki/Super_Mario_Land)
    [Super Mario Land 2: 6 Golden Coins](https://en.m.wikipedia.org/wiki/Super_Mario_Land_2:_6_Golden_Coins)
    [Tetris](https://en.m.wikipedia.org/wiki/Tetris_(Game_Boy))
    [Wario Land: Super Mario Land 3](https://en.m.wikipedia.org/wiki/Wario_Land:_Super_Mario_Land_3)

**Comment by soundsnow** [comment]
I saw your screenshots
but my Tetris is monochrome
is that GBC version?

**Comment by skylersaleh** [comment]
The special palettes are part of the GBC bootrom (rather than the game ROM). If you add one to the same folder as the  game ROM (named cgb_boot.bin) these will work exactly like a gameboy color would.
