### ISSUE TITLE
Chinese Garbled code

### ISSUE THREAD

**Issue by shooterspps** [skylersaleh/SkyEmu#200]
Chinese windows system
localization.c
After UTF-8 is transferred to UTF-8 BOM, there is no garbled Chinese

IconsForkAwesome.h
the icon is not garbled：
#define ICON_FK_PAUSE "\xef\x81\x8c"	#define ICON_FK_PAUSE u8"\uf04c"
#define ICON_FK_PLAY "\xef\x81\x8b"	#define ICON_FK_PLAY u8"\uf04b"
#define ICON_FK_FORWARD "\xef\x81\x8e"	#define ICON_FK_FORWARD u8"\uf04e"
#define ICON_FK_BACKWARD "\xef\x81\x8a"	#define ICON_FK_BACKWARD u8"\uf04a"
#define ICON_FK_FAST_FORWARD "\xef\x81\x90"	#define ICON_FK_FAST_FORWARD u8"\uf050"
#define ICON_FK_VOLUME_UP "\xef\x80\xa8"	#define ICON_FK_VOLUME_UP u8"\uf028"
#define ICON_FK_INFO_CIRCLE "\xef\x81\x9a"	#define ICON_FK_INFO_CIRCLE u8"\uf05a"
#define ICON_FK_SERVER "\xef\x88\xb3"	#define ICON_FK_SERVER u8"\uf233"
#define ICON_FK_LIST_OL "\xef\x83\x8b"	#define ICON_FK_LIST_OL u8"\uf0cb"
#define ICON_FK_EXCHANGE "\xef\x83\xac"	#define ICON_FK_EXCHANGE u8"\uf0ec"
#define ICON_FK_SITEMAP "\xef\x83\xa8"	#define ICON_FK_SITEMAP u8"\uf0e8"
#define ICON_FK_PENCIL_SQUARE_O "\xef\x81\x84"	#define ICON_FK_PENCIL_SQUARE_O u8"\uf044"
#define ICON_FK_AREA_CHART "\xef\x87\xbe"	#define ICON_FK_AREA_CHART u8"\uf1fe"
#define ICON_FK_SIGN_IN "\xef\x82\x90"	#define ICON_FK_SIGN_IN u8"\uf090"
#define ICON_FK_FILE_O "\xef\x80\x96"	#define ICON_FK_FILE_O u8"\uf016"
#define ICON_FK_CLOCK_O "\xef\x80\x97"	#define ICON_FK_CLOCK_O u8"\uf017"
#define ICON_FK_GAMEPAD "\xef\x84\x9b"	#define ICON_FK_GAMEPAD u8"\uf11b"
#define ICON_FK_FLOPPY_O "\xef\x83\x87"	#define ICON_FK_FLOPPY_O u8"\uf0c7"
#define ICON_FK_DESKTOP "\xef\x84\x88"	#define ICON_FK_DESKTOP u8"\uf108"
#define ICON_FK_KEYBOARD_O "\xef\x84\x9c"	#define ICON_FK_KEYBOARD_O u8"\uf11c"
#define ICON_FK_WRENCH "\xef\x82\xad"	#define ICON_FK_WRENCH u8"\uf0ad"
#define ICON_FK_HAND_O_RIGHT "\xef\x82\xa4"	#define ICON_FK_HAND_O_RIGHT u8"\uf0a4"
#define ICON_FK_FOLDER_OPEN "\xef\x81\xbc"	#define ICON_FK_FOLDER_OPEN u8"\uf07c"

**Comment by skylersaleh** [comment]
Could you post a screen shot of the garbled Chinese?

**Comment by shooterspps** [comment]
> Could you post a screen shot of the garbled Chinese so that I know what to look for/test?

Github Actions
![2023-1-8 0-44-27](https://user-images.githubusercontent.com/106127975/211161584-76139280-cd46-4100-a116-7272da047e41.png)

Native Build
vs2022 save as UTF-8 BOM
![2023-1-8 0-37-52](https://user-images.githubusercontent.com/106127975/211161722-ccfc994e-e70e-4a8b-b3bd-c7ee9b446dc9.png)
![2023-1-8 0-48-35](https://user-images.githubusercontent.com/106127975/211161731-c589d79f-cbfc-4cdc-8049-cc59a731a4d7.png)

**Comment by skylersaleh** [comment]
So, I think this is the result in an oddity on how MSVC treats u8 modified string literals. 

I submitted a fix that should fix it in theory. You can try a CI build here: https://github.com/skylersaleh/SkyEmu/pull/143

Let me know if you are still having issue.

**Comment by shooterspps** [comment]
The Chinese display is correct, thank you very much
