### ISSUE TITLE
DS landscape 1:1 side-by-side layout

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#203]
picture 1: ignore buttom navigation bar and rounded rectangle
picture 2 and 3: fixed
![image4](https://user-images.githubusercontent.com/109885044/211202714-43a75f19-f092-40db-b48f-2cf18b4be737.png)

**Comment by soundsnow** [comment]
D-Pad, Select/Start share same position with GBC/GBA

**Comment by skylersaleh** [comment]
Implemented in https://github.com/skylersaleh/SkyEmu/pull/363
