### ISSUE TITLE
add fullscreen in windows (F11) to SkyEMU 

### ISSUE THREAD

**Issue by elcorsico** [skylersaleh/SkyEmu#214]
i dev , thanks for working hard in this emu
possible to add option fullscreen (F11) in skyemu for windows 11 or other
thanks all dev and continue
kiss From France ;-)

**Comment by skylersaleh** [comment]
Hi Elcorsico, 

I just added a gui option and keybind for toggling fullscreen to the nightly build here(https://github.com/skylersaleh/SkyEmu/pull/143). Let me know if it works for you!

Thanks,

-Skyler

**Comment by elcorsico** [comment]
yeah dev , cool working for me , thanks for this 
good job
continue and thanks
excuse for my bad english lol
