### ISSUE TITLE
Nintendo DS Emulation 

### ISSUE THREAD

**Issue by NICOHACKER2021** [skylersaleh/SkyEmu#217]
Is the Nintendo DS emulation stable now?
I want to try to play NDS games, and they don't work, the screen is blank and the emulator slows down too. 
If so, I hope they fix it soon.

**Comment by skylersaleh** [comment]
Hey Nicohacker2021, 

The NDS core is still pretty far away from being stable/usable. It is expected that most games will not work in it in its current state. 

Thanks,

-Sky
