### ISSUE TITLE
Choose Save and State Folders/ BIOS Files for Android Phones (No Keyboard)

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#240]
I can't input texts. I have no keyboard
ImGui App
Choose a Folder for State
Choose a Folder for Save
![Screenshot_20230215-140850_Trebuchet](https://user-images.githubusercontent.com/109885044/218947188-07a0d9cf-feae-480f-80a9-ad9687c4b360.png)
Choose a File for BIOS
![Screenshot_20230215-140934_Trebuchet](https://user-images.githubusercontent.com/109885044/218947320-d275c9c0-907b-4620-a1b9-c965354c75a7.png)

**Comment by skylersaleh** [comment]
I pushed some fixes so that these settings can be altered on android without keyboard input.
