### ISSUE TITLE
delete selected save or state files

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#262]
delete files with checkbox

I remember some emulators support this
Mupen64Plus AE delete all data
DuckStation delete states, delete/format/new memory card
AetherSX2 delete states, delete/format/new memory card
MasterEmu delete wipe all states
WonderDroid delete states/daves
GBCC delete saves

**Comment by skylersaleh** [comment]
Added in https://github.com/skylersaleh/SkyEmu/pull/321
