### ISSUE TITLE
powerful gb game maker, debugger, trainer and emulator

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#270]
I've heard of an open source GB game maker.  It has a GB emulator built in.  So I thought in reverse, why can't the GB emulator have a built-in game maker?  Its GUI is very similar to SkyEmu.  I was looking forward to develop GB game on Android phone without code knowledge.

![screenshot_win_1_v3](https://user-images.githubusercontent.com/109885044/224466520-e7c143f6-9a8b-4777-9444-fdd5f2f5e723.png)
![screenshot_win_2_v3](https://user-images.githubusercontent.com/109885044/224466544-5913f302-c53d-4876-985d-911bf58a5a59.png)
![screenshot_win_3_v3](https://user-images.githubusercontent.com/109885044/224466556-2f70adf4-6a7e-48ef-b44b-c7ab3f8dcdba.png)
![screenshot_win_4_v3](https://user-images.githubusercontent.com/109885044/224466557-f9104dc6-11e4-4666-b047-15ae67bec287.png)

**Comment by soundsnow** [comment]
By the way, improve the GUI of SkyEmu

**Comment by Felipefpl** [comment]
> By the way, improve the GUI of SkyEmu

This is too generic, how is the author gonna improve something if you dont tell him what is wrong or what could be better? Personally i dont like the fact the GUI doesnt follow the traditional windows style but this is only my opinion and not a good one to convince anyone to make changes, i/everyone can use the emu as it is.

**Comment by skylersaleh** [comment]
A full Game Boy game engine is out of scope for this project.
