### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by GHRoss** [skylersaleh/SkyEmu#277]
Is there a build that includes the REST API?

**Comment by GHRoss** [comment]
Nice, thank you. Calls appear to permanently hang on Windows at least. :(

Trying on Ubuntu but getting this error... "There is no application installed for executable files".

Are there any dependencies I need to install first?

**Comment by skylersaleh** [comment]
Hmm, I haven't tried it on Windows before. I'll take a look. 👍

**Comment by skylersaleh** [comment]
If you make something cool with it, you should post a picture or video! I'm really interested to see how people use this API.

**Comment by GHRoss** [comment]
For sure! I'm currently trying to get the current score of a running Tetris DX game to display on a webpage over a websocket.

I'm using the read_byte endpoint but not getting the result I'd expected. The value from the endpoint call is 80020000 and the in-game score is 280. Do you know what the conversion I need to do here is? Or is it perhaps that I'm getting the order of the addresses incorrect? It looks like the score is there, just not in order?

**Comment by skylersaleh** [comment]
That looks a lot like the Binary Coded Decimal format that a lot of GB games use for numbers displayed in GUIs. 

Basically, they take groups of two digits from right to left, encode them as a hexadecimal number and store them as a byte. 

So for example the decimal number 12345678 would be encoded as the following 4 bytes {0x78,0x56,0x34,0x12}.

**Comment by skylersaleh** [comment]
Could you send me the REST URLs you are requesting?

**Comment by GHRoss** [comment]
Not to worry, all sorted now.
