### ISSUE TITLE
Warriors of Might and Magic (USA) (En,Fr,De) GBC corrupt hud

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#28]
during gameplay the HUD down the bottom is corrupt

**Comment by skylersaleh** [comment]
Confirmed to still exist on Dev 9-4-2022. 

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/7118296/188365564-c2b36965-c9da-40b0-a122-5cf268ea6c91.png">

**Comment by skylersaleh** [comment]
<img width="1392" alt="Screen Shot 2022-09-18 at 1 09 16 PM" src="https://user-images.githubusercontent.com/7118296/190926612-52f07b1c-95eb-4c68-9069-3af691fccdd4.png">
