### ISSUE TITLE
Non game (save,state...) their own default file paths

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#282]
3380(13.09GB).zip+43(1.46GB).zip+65(345.08MB).zip=3488(15GB).zip
I hope the loading file list can be faster, please don't let other files (saves, states...) appear in the game file path by default
I'm taking the size of GBA games as an example, they will definitely take a while to be scanned, more on older or low end devices

**Comment by skylersaleh** [comment]
There is already a setting for this in the latest build.
