### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#284]
https://docs.libretro.com/library/compatibility/gbc/
https://docs.libretro.com/library/compatibility/gba/
https://docs.libretro.com/library/compatibility/ds/

I tested the GBA game Phantasy Star Collection and it has the same bug as the old VBA-M.
Digital Eclipse logo sound effect is missing
Bugs on these pages are likely to occur in SkyEmu

**Comment by skylersaleh** [comment]
Make sure you use a GBA bios.
