### ISSUE TITLE
D-Pad Rotation

### ISSUE THREAD

**Issue by soundsnow** [skylersaleh/SkyEmu#287]
Video - Screen Rotation: 0, CW 90°, 180°, CCW 90°
Input - D-Pad Rotation: 0, CW 90°, 180°, CCW 90°
Doodle Jump GBA (Game Boy Micro)
Up is Left, Down is Right, Start/Select is Pause
![image225](https://user-images.githubusercontent.com/109885044/230249391-b529c61e-2f72-4cc9-ad00-486ee133a792.png)

**Comment by skylersaleh** [comment]
The onscreen controller will work correctly by just rotating the phone (if the phones autorotate is turned off). 

The input configuration settings can be used to rotate the dpad input appropriately.
