### ISSUE TITLE
HTTP server's /run endpoint does nothing

### ISSUE THREAD

**Issue by kran6a** [skylersaleh/SkyEmu#290]
Title.
The pause mode is set [here](https://github.com/skylersaleh/SkyEmu/blob/7b42bbd2bc921fafec45d00888416187c6c2b7f2/src/main.c#L4498) when running in server mode and is not overriden by calling the `/run` endpoint.

Steps to reproduce:
1. `./SkyEmu http_server 9090 ./roms/rom.gb`
2. open `http://localhost:9090/run`
3. await 5 seconds
4. open `http://localhost:9090/screen` and see the black screen.

**Comment by skylersaleh** [comment]
That is intentional. The http_server mode is designed to be very thin to have really low latency interaction with the API. So, it doesn't have a concept of real time anymore (it doesn't even open up a host window). You can still use SkyEmu with the control server with the GUI active by not specifying the http_server command, but having the option enabled in the GUI. This will allow pause and run to work normally.

**Comment by kran6a** [comment]
Thanks for the response, my use case was having a SkyEmu instance on a headless raspberry pi running at home and playing from multiple devices/screens/places by streaming the emulator output and button inputs while sharing the game library and saves.

Having the option to toggle real time mode while in headless mode would be handy for this use case but I understand this is not a common use case.

**Comment by skylersaleh** [comment]
For your use case, are you trying to design your own frontend webpage?

**Comment by kran6a** [comment]
Yes, it would just show a video/canvas depending on the difficulty of converting the emulator frame stream to a video format and forward keypresses to the emulator.

**Comment by skylersaleh** [comment]
For a use case like this, you probably want to run the control loop for ticking at the client side. That way you can match the frame rate for the browser and take advantage of some of the optimizations that SkyEmu does when it steps more than 1 frame. 

Check out this jsfiddle for an example prototype. 

https://jsfiddle.net/e4ct1x2h/39/

**Comment by skylersaleh** [comment]
The previous jsfiddle was making use of a bug that has since been fixed in dev. You will need to update the number of step frames as shown in the below jsfiddle to get the correct behavior after the bug fix. 

https://jsfiddle.net/7kv2anzy/3/
