### ISSUE TITLE
 Monster Gate (Japan) - Screen Covered With Dashes With Max Cards

### ISSUE THREAD

**Issue by HeroponRikiBestest** [skylersaleh/SkyEmu#292]
If you fill all 10 of your cards/items slots, the screen will be covered with dashes, and this will show up everytime you open your list of cards (which is pretty much all the time, since you need it to use items)
Seems to occur on Rev 1 as well, and the save seems to work there too, but most testing was done with the original version.

This issue was fixed in mGBA in commit https://github.com/mgba-emu/mgba/commit/4ce9b83362ad66b1421afea7372adfc753bce97c between releases 0.1.0 and 0.1.1, and the game has continued functioning properly from there until now, as of the latest nightly..

Apparently, this is the result of a documentation error in gbatek. While I don't know of any existing correct documentation, it seems like mode0 can only use the first 64k of vram for background tiles.

To reproduce, load the following save file, choose to continue, and immediately walk to the right; your 10th card slot will be filled up, and the card screen will display, showing the issue.
[Monster Gate (Japan).sav.zip](https://github.com/nba-emu/NanoBoyAdvance/files/11402986/Monster.Gate.Japan.sav.zip)

![skyemu](https://user-images.githubusercontent.com/50224630/236600572-e3f35af2-15e8-4683-bc04-6c18bf62efac.png)

```
file: Monster Gate (Japan).gba
sha256: <3b48a60acb92f0ca17772a0d551656cd550968cfa720e83f8abe48bd0064d5ad>
```
Tested on latest commit on browser
Tested on Linux Mint 21.1

**Comment by skylersaleh** [comment]
Thanks for reporting this bug and the detailed information of how to reproduce and the root cause. 

It was fantastic. 

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/7118296/236694088-9051fbc4-a13b-41cf-b3fa-d7d9c2548858.png">

I just submitted a fix to the dev branch for this. The CI build should incorporate this here: https://github.com/skylersaleh/SkyEmu/pull/143

**Comment by HeroponRikiBestest** [comment]
Further research done at nanoboy, added with https://github.com/nba-emu/NanoBoyAdvance/commit/87396726e513863bb9d1612a3d6a29ca6f72720a


> If this is it then it is indeed what I suspected: open bus from the internal background VRAM bus. This means that the data that was most recently (successfully) read from background VRAM is read and interpreted as tile data.
> In the simple case where only one background layer is enabled this is the tile map entry that was fetched before the tile data.
> With multiple background layers the situation most likely is more complicated and the data that is returned could be map or tile data from another background layer.
> Monster Gate still works with my change, so that's good.
> 
> I think I pretty much confirmed that it's open bus and background layers can affect other background layers.
> Luckily this is very easy to support with NBA's cycle-accurate PPU emulation.
> Other emulators are advised to just return 0 for the out-of-bounds accesses, since they do not replicate the proper VRAM access patterns for open-bus to return the right values.
