### ISSUE TITLE
Hide pause, fast forward in UI

### ISSUE THREAD

**Issue by GHRoss** [skylersaleh/SkyEmu#294]
Is it possible to hide these buttons already?

**Comment by skylersaleh** [comment]
The dev builds at the link below have an autohide feature you can enable in the settings. 

https://github.com/skylersaleh/SkyEmu/pull/143

When it is turned on, the buttons will auto hide when playing a game if there is no other panels open. Let me know if that is what you are looking fo.

**Comment by GHRoss** [comment]
It is! Thank you! I'veb been using the hell out of the REST server.
