### ISSUE TITLE
simple request

### ISSUE THREAD

**Issue by hunter1026** [skylersaleh/SkyEmu#296]
it would be nice if the touch controls stayed on the screen instead of fading away. its really annoying that the buttons dissapear. if not atleast make it to where theres a button that toggles the on screen controls on or off but i would really like for them just to stay on.

**Comment by skylersaleh** [comment]
There is a setting you can turn off in the dev build here: https://github.com/skylersaleh/SkyEmu/pull/143 to turn off the auto hiding of the controls. 

<img width="921" alt="Screen Shot 2023-06-05 at 9 15 55 PM" src="https://github.com/skylersaleh/SkyEmu/assets/7118296/8a8947f7-12fc-4a56-ba43-bf0458085dd2">

**Comment by hunter1026** [comment]
and also, can you switch the start and select buttons so that select is on the left and start is on the right so that its like an actual gameboy?

**Comment by hunter1026** [comment]
thanks! i didnt know there was a dev build

**Comment by skylersaleh** [comment]
Give it a shot! It also has the select and start buttons swapped. 👍 

Its pretty stable at this point, but there is still one bug with Boktai 1 that is preventing its release.
