### ISSUE TITLE
Worms Armageddon (E) (M6) [C][!] missing background

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#30]
choose quick game and the background is missing

**Comment by skylersaleh** [comment]
I'm not seeing a background in SameBoy either.

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/7118296/188365078-116547c7-b64f-4c42-a21b-9a01ba1ca746.png">

Is there something I might be missing?

**Comment by benderscruffy** [comment]
https://github.com/LIJI32/SameBoy/issues/91

**Comment by benderscruffy** [comment]
just checked it on real hardware
