### ISSUE TITLE
HTTP server doesn't seem to work if not ran with `http_server` command line option on Windows

### ISSUE THREAD

**Issue by OFFTKP** [skylersaleh/SkyEmu#306]
SkyEmu http_server <port> <path> works on windows, but running SkyEmu normally and enabling http server doesn't seem to

**Comment by skylersaleh** [comment]
Any ideas why this might fail?

**Comment by OFFTKP** [comment]
I don't have a fully set up debugging environment on windows but one thing I tried is commenting out every single server->mutex.lock / unlock and it worked. I wonder if it's deadlock related. It's weird I can't reproduce in linux though.

**Comment by skylersaleh** [comment]
Dillon and I were able to get this working after https://github.com/skylersaleh/SkyEmu/commit/ed089a24153391ab8681f7170f7df7943a27ca37

Let me know if it works on your machine.

**Comment by OFFTKP** [comment]
Yup, works now!
