### ISSUE TITLE
Nightly v3 Android release has incorrect menu scaling

### ISSUE THREAD

**Issue by FreyrDev** [skylersaleh/SkyEmu#311]
In the nightly android release from the v3 tracking page #143, the scale of all of the UI elements is too large:

| | Android Release v3 | PWA
--:|:--:|:--:
ROM Loading Menu | ![Screenshot_20230804-212532](https://github.com/skylersaleh/SkyEmu/assets/95385132/b4fdb4fd-ebf6-4b15-a525-160210e36027) | ![Screenshot_20230804-213301](https://github.com/skylersaleh/SkyEmu/assets/95385132/c6ed7553-d50d-433a-93cf-7400f77c6711)
Settings Menu | ![Screenshot_20230804-212543](https://github.com/skylersaleh/SkyEmu/assets/95385132/65289ed1-0e83-4f24-93b6-cc7185b0cdff) | ![Screenshot_20230804-213304](https://github.com/skylersaleh/SkyEmu/assets/95385132/f7d70acc-45e7-4802-806e-78dc72d9012a)

This causes some text to be cut off on the right hand side of the screen, as well as the menu being almost unscrollable due to the touchscreen control preview filling the screen:

![Screenshot_20230804-212631](https://github.com/skylersaleh/SkyEmu/assets/95385132/21226048-19a0-4d97-b337-41f8d075f689)

I wonder if this is related to my display size? My phone screen is 1600x720 (20:9).

**Comment by skylersaleh** [comment]
Hi I just pushed a commit to dev that I think may fix this. 

Can you try this by downloading the latest build in about 15 mins from here: https://github.com/skylersaleh/SkyEmu/pull/143

**Comment by FreyrDev** [comment]
Yep, that works now, thanks!
