### ISSUE TITLE
Nightly v3 Android release touchscreen controls overlap with Android navigation controls

### ISSUE THREAD

**Issue by FreyrDev** [skylersaleh/SkyEmu#312]
On the right hand side of this screenshot from the v3 page #143 you can see that the android navigation controls are on top of the emulator controls:

![Screenshot_20230804-213232](https://github.com/skylersaleh/SkyEmu/assets/95385132/ddeaa48c-66c2-41a1-972e-22cc37847e25)

This issue isn't present in the PWA:

![Screenshot_20230804-213141](https://github.com/skylersaleh/SkyEmu/assets/95385132/6b52b2ec-9d38-4d72-b9c9-a5ab262dfbcb)

Ideally the navigation control would be hidden while playing, like with watching YouTube videos on full screen, but taking the navigation into account like the PWA would work as well.

**Comment by skylersaleh** [comment]
I just pushed a commit to dev that should hide the nav bar to dev. Could you test it in about 15 mins when the CI finishes building. 

https://github.com/skylersaleh/SkyEmu/pull/143

**Comment by FreyrDev** [comment]
Yep, thanks
