### ISSUE TITLE
Black rectangles in Minish Cap without BIOS

### ISSUE THREAD

**Issue by RetroEdit** [skylersaleh/SkyEmu#313]
Certain sprites are just displayed as black rectangles or otherwise distorted.

It happens during the opening cutscene with Vaati, but it's also apparent every time you shrink during the shrinking cutscene.

*Edit*: it just occured to me that this is a common issue I've seen several years back without BIOS in other emulators, and I was having trouble loading the BIOS, so this is probably more an issue with SkyEmu's provided BIOS alternative.

Tested on: 104c287

Left is Android without BIOS, right is Windows with BIOS:
![SkyEmu_TMC_shrink](https://github.com/skylersaleh/SkyEmu/assets/30182911/e809a343-e322-44ea-831d-a19c21df8ea5)

I also did a quick test with Windows without BIOS, and it had similar issues.

**Comment by skylersaleh** [comment]
Yep, definitely a COG BIOS issue. I filed an issue on that github referencing this so that we don't lose track of it.

**Comment by DenSinH** [comment]
This could be closed once https://github.com/skylersaleh/SkyEmu/blob/dev/src/gba_bios.h is regenerated from the latest version of the COG BIOS
