### ISSUE TITLE
Minish Cap: "unlock" sound effect issue

### ISSUE THREAD

**Issue by RetroEdit** [skylersaleh/SkyEmu#315]
I noticed a general sound effect issue with Minish Cap. The "unlock" sound effect seems to output notes that are more shrill and short than on real console.

Reproduced on 104c287b30c1f0ddc36d1970def9c82ca402b91b on both Windows and Android, with and without BIOS.

Here's a comparison video. For testing, I used the early Business Scrub cutscene you get in the first few minutes of gameplay. First I ran the cutscene in SkyEmu, then I ran it in NanoBoyAdvance.

https://www.youtube.com/watch?v=d9TL7ItKl2k

Here's a savestate shortly right before the cutscene; you just have to press 'A' for the sound to be played: [Legend of Zelda, The - The Minish Cap (USA).slot0.state.png.zip](https://github.com/skylersaleh/SkyEmu/files/12304829/Legend.of.Zelda.The.-.The.Minish.Cap.USA.slot0.state.png.zip)

**Comment by skylersaleh** [comment]
Thanks, was able to reproduce this issue. I'll start looking into it.

**Comment by skylersaleh** [comment]
Turns out I had a bad read mask on SOUNDCNT_X which made it look like the PSG notes finished playing immediately to the game, so the audio engine ended up playing the PSG notes way too quickly causing only small blips of the noise to come out.
