### ISSUE TITLE
NDS touchscreen clicks are not where the mouse pointer is.

### ISSUE THREAD

**Issue by pivotiiii** [skylersaleh/SkyEmu#319]
Hi,
I only tried this with the web build on Windows but the lower screen does not actually click where the mouse pointer is. Depending on where on the screen I click it really is not even close. As far as I can tell this happens regardless of window size/ scaling.
In games like Prof. Layton 4 this is pretty visible.

https://github.com/skylersaleh/SkyEmu/assets/17112987/991a51d2-75e2-41b9-9e36-9f6e9301c786

**Comment by skylersaleh** [comment]
A few questions. 

1) Is there any scale factor applied by the website (ie. Page zoomed in)?
2) Are you using a specific firmware? 
3) Do you have any side panels open?

**Comment by pivotiiii** [comment]
1. No scaling or anything, the settings in the side panel are all on default as well.
2. I used the firmware files from the DS, I don't know if there are different versions. I tested it without the files just now and the touch inputs are correct again!
3. No side panels and the menu bar on top was on auto hide.

**Comment by skylersaleh** [comment]
This likely indicates bad calibration data of the touch screen in your NDS firmware dump. I'd try redumping your firmware.bin if you can.

**Comment by pivotiiii** [comment]
This was the issue. I just dumped the firmware from my phat DS again using https://github.com/DS-Homebrew/dsbf_dump and its perfect now. Interestingly enough when dumping the DS firmware on a DSi console the firmware.bin has half the size and does not work.
