### ISSUE TITLE
Mother 3 - scrolling corruption

### ISSUE THREAD

**Issue by a-hurst** [skylersaleh/SkyEmu#320]
Hi there,

Just trying out this emulator to get back into some GBA era games, the LCD filters and color correction look great! I did notice a bug though when trying out the English translation (v1.1) of MOTHER 3. Basically, when you walk around for a bit, the background sprites seem to "stick" occasionally so the background gets increasingly garbled over time: 
![Screenshot_20230814_114339](https://github.com/skylersaleh/SkyEmu/assets/18648066/f68adcac-a462-4c2a-8643-594b5857a192)

Plugging the exact same ROM into NanoBoyAdvance, I get no such issues (same location, for reference of what the background should look like):
![Screenshot_20230814_114556](https://github.com/skylersaleh/SkyEmu/assets/18648066/c88eef1a-2582-4c05-bcd6-bf0759bd34eb)

Enabling/disabling filters and ghosting settings didn't have any effect, so I'm assuming it's a glitch with the emulation itself? Also, this bug happens in both SkyEmu v3 (where I originally noticed it) as well as SkyEmu v2, so it's not a recent regression. This is using the official Linux binary from the GitHub releases page on a Fedora 38 system. Let me know if there's any other details I can provide!

**Comment by skylersaleh** [comment]
Are you using an official GBA BIOS?

**Comment by a-hurst** [comment]
@skylersaleh I am! Without the BIOS the results are the same. The same BIOS renders the game normally without glitches with NanoBoyAdvance, so I'm reasonably sure it's a good BIOS dump. Are there any additional details I can provide?

**Comment by OFFTKP** [comment]
Can also reproduce, only on Desktop - not on Web.

**Comment by skylersaleh** [comment]
> Can also reproduce, only on Desktop - not on Web.

Did you happen to capture a savestate that I could use to try to reproduce on my end?

**Comment by OFFTKP** [comment]
![Mother 3 (Eng  Translation 1 1) slot1 state](https://github.com/skylersaleh/SkyEmu/assets/21157395/1455cccc-a200-48fe-b385-3a2ce63dc588)

**Comment by skylersaleh** [comment]
I just submitted some fixes to dev that hopefully fixes this. Can you give it a test?

https://github.com/skylersaleh/SkyEmu/pull/321
