### ISSUE TITLE
"Sleep" mode in games doesn't turn off screen

### ISSUE THREAD

**Issue by RetroEdit** [skylersaleh/SkyEmu#323]
Certain GBA games like Shrek 2 GBA have a sleep mode that takes the console into a low power mode and turns off the screen.

However, it doesn't properly turn off the screen like my AGS-101 does. On my AGS-101, the behavior in Shrek 2 is a flash to white, then full black until you press the key sequence `l` shoulder + `r` shoulder + `Select`, and then a brief period of white screen when it resumes until it properly resumes the game. On SkyEmu by contrast, it does sort of "sleep" until that key sequence, but the emulator screen remains a freeze frame of the actual game the entire time.

Comparing SkyEmu to to other emulators, SkyEmu at least has a frontend partly simulates sleep freeze behavior, unlike its contemporaries mGBA (https://github.com/mgba-emu/mgba/issues/1482) and NanoBoyAdvance; however, mGBA and NanoBoyAdvance both also have those white frames at least.

**Comment by skylersaleh** [comment]
Some changes I just pushed into v4 should fix this. 

https://github.com/skylersaleh/SkyEmu/pull/321

**Comment by RetroEdit** [comment]
I did another comparison using 285d70f1a6cf91e3bec10be5a9aca8cc392954d1. The screen does turn off now; however, I will make an additional note that it seems to exit sleep mode much faster than my real hardware does. Or maybe the screen turns on faster?

**Comment by skylersaleh** [comment]
There is probably some boot up delay when exiting "halt" mode on the CPU, but I don't think I've seen any HW research on this behavior.

**Comment by RetroEdit** [comment]
b7880443ad56382dfaec7423d7bdff432e5e9d89 fixed the issue in the title; any further issues with STOP mode, so I'll close this issue. Any further inaccuracies with STOP mode could be created as a separate issue.
