### ISSUE TITLE
Android: Build to 32 bit APK

### ISSUE THREAD

**Issue by TheHacker19** [skylersaleh/SkyEmu#324]
I tried installing the Android version but it failed.

I found out that this is caused by the emulator being compiled to 64bit.

I was wondering if there was a way to compile it to 32bit or if I should use the web app instead?

**Comment by skylersaleh** [comment]
Try to use the latest Android build here: https://github.com/skylersaleh/SkyEmu/pull/321

Not sure how well it will perform as most 32bit processors are pretty old at this point.
