### ISSUE TITLE
Android 32-bit crashes when trying to open

### ISSUE THREAD

**Issue by darkrunner09** [skylersaleh/SkyEmu#329]
Hello, I have an Android 9 operating on 32-bits, and when I try to open SkyEmu, it simply closes. It was tested with the latest build from GitHub Actions.

![Screenshot_20230905-130859](https://github.com/skylersaleh/SkyEmu/assets/143284417/91daa7a4-7d31-4330-a759-f00e2a31b9ff)

**Comment by darkrunner09** [comment]
Adding that this happens regardless of the build, as I've tested it since the 32-bit version was released.

**Comment by skylersaleh** [comment]
@darkrunner09 Did you find a fix or something?

**Comment by darkrunner09** [comment]
"No, I will check the logs if it happens again with the latest commits. I just didn't do this earlier due to lack of access to a computer."

**Comment by darkrunner09** [comment]
The last build worked perfectly, the app opened without any issues. I think this issue can be closed.
