### ISSUE TITLE
WebApp:  Resetting game 500-4000 times freezes the emulator

### ISSUE THREAD

**Issue by KittyPBoxx** [skylersaleh/SkyEmu#330]
_(I promise this is a real use case)_

### REPRODUCE

Load a game and hit the reset key 4000 times... 
OR
In the console set `FS.MAX_OPEN_FDS = 10` and reload the game a few times.

### TECHNICAL

When roms are loaded the FS streams don't get closed. So each time the game is reset you can see `FS.streams.length` increases. When this hits the FS.MAX_OPEN_FDS limit (of 4096) the emu stops being able to perform file operations and freezes.

Each time the reset button is pressed it opens the stream to the rom and any bios/firmware files that are loaded. When using the menu to reload (instead of the reset key), all of the streams get opened twice. So the worse case scenario is when reloading NDS games from the menu (with all the bios and firmware loaded) as this leaves 8 streams open each time. 

The open streams are not in use and seem to be safe to close and remove from the list e.g 
`FS.streams.forEach(s => { try {FS.close(s) } catch (e) {} }); FS.streams = FS.streams.filter(n => n);` 

### USE CASES

I suspect the most common use case for this would be for pokemon scripted legendary shiny hunting where an automated program is doing inputs and resetting the game a thousands of times. 

My personal use case is I've recently switched to use skyemu as the core for a multi game loading zone randomizer (i.e when you go through a loading zone in one game you come out in another game). And have had some bug reports that it crashes after playing for a few hours.

**Comment by skylersaleh** [comment]
Thats quite odd. I'll take a look in a few days.

**Comment by skylersaleh** [comment]
This should fix the rom double loading issue. https://github.com/skylersaleh/SkyEmu/pull/331

I still need to look into why the handles stay open though.

**Comment by skylersaleh** [comment]
@KittyPBoxx Can you check if the changes that have recently been merged resolved these issues?

**Comment by KittyPBoxx** [comment]
Thank you! Can confirm this solves the issue 😊

There's a few streams still open (2 to 'dev/tty' and 1 to 'dev/tty2'). I assume these are used for logging? although it doesn't seem to cause any issue if I close them. 

There's also 2 extra null entries getting put in the list (1 the first time any game/bios is loaded the other when ds firmware is loaded). Null entries means the stream is getting closed but for whatever reason not being removed... These null entries count towards the MAX_OPEN_FDS's but as it only seems to happen twice I don't think there's any risk of hitting the limit.
