### ISSUE TITLE
Top Gun - Combat Zones (USA) cannot start a new game (GBA)

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#34]

**Comment by skylersaleh** [comment]
Hi Benderscruffy,

Thanks for doing so much game testing. When reporting GBA game bugs can you report if you experienced the bug while using an official BIOS or not?

SkyEmu will show the GBA boot screen(picture below) when it is using the official BIOS. 
![image](https://user-images.githubusercontent.com/7118296/178296442-7aa19b45-2297-4b12-bd5e-7cb4cc8f2131.png)

**Comment by skylersaleh** [comment]
Fixed in dev. https://github.com/skylersaleh/SkyEmu/pull/40
