### ISSUE TITLE
Question: launch android apk with arguments

### ISSUE THREAD

**Issue by stevenpi** [skylersaleh/SkyEmu#365]
Hi there! I'm working on a hobby project which serves as a general purpose rom launcher (for private usage).

In this rom launcher (an android app), i'd like to launch the skyemu app with argument i.e. `--rom pokehack.gba`, so that the skyemu app automatically starts loading the passed rom. Basically like in windows, where I can invoke a command like this: `emulator.exe --rom C:\myrom.gba`

Unfortunately i'm a beginner in android development, therefore I don't know if that what I want to achieve is possible. 
So, is it possible to launch the skyemu android app, with a specific intent?

**Comment by skylersaleh** [comment]
This was implemented in https://github.com/skylersaleh/SkyEmu/pull/321

The command line am start arguments for this are: 

The player `am start` arguments that should be used are: 
```
-n com.sky.SkyEmu/com.sky.SkyEmu.EnhancedNativeActivity
  -a android.intent.action.VIEW
  -d {file.uri}
  --activity-clear-task
  --activity-clear-top
```
