### ISSUE TITLE
[Feature Request] Android Native Build

### ISSUE THREAD

**Issue by skylersaleh** [skylersaleh/SkyEmu#37]
This issue is to track the feature request for an Android Native build to create SkyEmu.apk

In theory the current code base supports this, but the CI infrastructure and build system need updates to produce the android apks. 

This request was forked out of this issue: https://github.com/skylersaleh/SkyEmu/issues/36#issue-1300935444

**Comment by Dionicio3** [comment]
Hey I noticed that there's some Android related stuff in GitHub Actions, but it seems to just be some source code. Is there any plans to have precompiled apks soon? Or, at least have it so that directories aren't hardcoded in the source?

**Comment by skylersaleh** [comment]
> Hey I noticed that there's some Android related stuff in GitHub Actions, but it seems to just be some source code. Is there any plans to have precompiled apks soon? Or, at least have it so that directories aren't hardcoded in the source?

Hey @Dionicio3, we now have automatic builds for Android here: https://github.com/skylersaleh/SkyEmu/pull/143

Still very early, but playable.
