### ISSUE TITLE
when you press v (default key to tap on NDS) the emulator crashes out 

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#375]
using the latest version
 when you press v (default key to tap on NDS) the emulator crashes out

**Comment by skylersaleh** [comment]
Can you provide more details (ie. OS, does it only occur on one game, any other keys pressed besides v, etc.)? 

I am having a hard time reproducing this.

**Comment by benderscruffy** [comment]
windows 11 and it happens with every game you load
doesnt matter what key you assign to tap on nds it will crash out when you press the key

**Comment by benderscruffy** [comment]
Any updates on this as I can't play any NDS game as they all crash out

**Comment by skylersaleh** [comment]
I've had a few people try to reproduce this on their machines but we can't seem to figure out how to reproduce this crash. 

Does it happen when you click the touch screen with your mouse instead of using the tap keybind?

**Comment by benderscruffy** [comment]
Yes

**Comment by skylersaleh** [comment]
Okay, and by crashing, does the entire emulator crash (with the window going away), or does the game inside the emulator crash (still letting you load another game)?

**Comment by benderscruffy** [comment]
The entire emulator crashes

**Comment by skylersaleh** [comment]
A few more questions: 

Does it happen when a GBA game is loaded and press the tap key or click on the screen?
Does it happen both with and without a NDS Firmware.bin provided?

**Comment by benderscruffy** [comment]
it  doesnt happen when a gba game is loaded
it doesnt happen when you do not have firmware.bin 
it only happens when you have firmware.bin

**Comment by benderscruffy** [comment]
ok i just redumped my firmware and bios from my NDS and SkyEmu is working now
must of been a corrupt firmware
sorry about that
