### ISSUE TITLE
[NDS] Madden 06 - Broken Character Models

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#392]
![Screenshot 2024-01-03 161417](https://github.com/skylersaleh/SkyEmu/assets/2696404/7e738cc4-dd56-43a2-af7d-78105a530c29)

**Comment by skylersaleh** [comment]
This seems fixed with the changes put in for NFS. 

<img width="1392" alt="image" src="https://github.com/skylersaleh/SkyEmu/assets/7118296/26d10e6a-8ec5-47ef-a4f7-4be5694c80ae">
