### ISSUE TITLE
[NDS] de Blob (USA) (Proto) could not access save date error

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#405]
![Screenshot 2024-01-06 074018](https://github.com/skylersaleh/SkyEmu/assets/2696404/27841bbf-f9d6-4118-8fa9-1847385431e4)

**Comment by skylersaleh** [comment]
Looks like this game isn't in my ROM database. Is there any details anywhere on what kind of backup it is using (ie. FLASH, EEPROM, NAND) and its size?

**Comment by benderscruffy** [comment]
this loads in Desmume
it has BackupDevice  size = 4 Kbit
