### ISSUE TITLE
[NDS] Advance Wars - Dual Strike (USA, Australia) menu is black and keeps rotating (cant start a new game or choose options)

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#413]

**Comment by skylersaleh** [comment]
This seems to be a regression between V3 and current dev, I'll try to bisect it to find the offending change.

**Comment by skylersaleh** [comment]
Okay, I narrowed it down to this commit where I swapped from flat lighting to vertex lighting. 

https://github.com/skylersaleh/SkyEmu/commit/c95d04c9b776e216481881b753051dbc97a21fb9

I must have missed a needed condition.
