### ISSUE TITLE
[NDS] Animal Crossing: Wild World - blocky mask transition

### ISSUE THREAD

**Issue by bannmannutt** [skylersaleh/SkyEmu#418]
The circular transition in Animal Crossing: Wild World is weirdly blocky (I don't really know how to describe it properly, but it's immediately noticeable)

**Comment by skylersaleh** [comment]
Can you confirm that it still happens in the latest dev (and if you can, could you take a screenshot)? 

I submitted a fix that I thought fixed this a few days ago

**Comment by bannmannutt** [comment]
It appears I had an older version of the dev branch cached, upon reload, it's fixed itself
