### ISSUE TITLE
[NDS] touchscreen activated by touch when in settings

### ISSUE THREAD

**Issue by bannmannutt** [skylersaleh/SkyEmu#425]
Video showing what I'm talking about:
https://youtu.be/049z9RjzwPA?si=w9cKeGihCxAnkLli

**Comment by skylersaleh** [comment]
Can you test out if this change fixes things on your end?

**Comment by bannmannutt** [comment]
yeah I'll do that once the web build finishes

**Comment by bannmannutt** [comment]
It has been fixed
