### ISSUE TITLE
Pokemon FireRed/LeafGreen - Sprites are missing from intro of game

### ISSUE THREAD

**Issue by DeezY48** [skylersaleh/SkyEmu#440]
Hi, In beginning intro to pokemon Firered and Leafgreen where professor Oak talks to you and where you pick your character, Professor Oaks and the male/female protagonist sprites are missing. The game seems fine otherwise but I am only at the beginning of the game.

Thank you

**Comment by skylersaleh** [comment]
Can you insure that you are utilizing a dump of an official GBA BIOS and not the community BIOS included in SkyEmu?

**Comment by DeezY48** [comment]
I got a gba BIOs and it worked
