### ISSUE TITLE
Golden Sun - Depth issues

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#45]
using offical Bios
The carpet is rendered over character sprites
here is a save just continue game
[Golden.Sun.USA.Europe.zip](https://github.com/skylersaleh/SkyEmu/files/9091615/Golden.Sun.USA.Europe.zip)

**Comment by skylersaleh** [comment]
Thanks for reporting this. I have fixed it in dev. 
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/7118296/179420113-b5422823-ff5f-4e02-ba1c-dc979b65d7a2.png">
