### ISSUE TITLE
Issues with cheat codes

### ISSUE THREAD

**Issue by DeezY48** [skylersaleh/SkyEmu#450]
So, I have been trying to find an action replay code for Pokemon Fire Red/Leaf Green that lets me get infinite rare candies, but all the ones I find don't work. When I put a code into the box and click the checkmark to confirm it, it turns some of the code in 7FFFFFF. I'm not sure if it's the emulator or if I just don't have the right codes. Btw I have a gba bios.

**Comment by skylersaleh** [comment]
This was a bug that was fixed in the V4 dev branch. 

You can access it here: https://github.com/skylersaleh/SkyEmu/pull/321
