### ISSUE TITLE
STRH r15 is wrong

### ISSUE THREAD

**Issue by Jaklyy** [skylersaleh/SkyEmu#458]
it's currently implemented (at least on the nds arm 9) as pc - 4 when it should be pc + 4.
may or may not also be wrong for gba/arm7 as well, haven't tested.

this test rom is the one i used to reproduce the results: 
my 3ds gets 0xB70 for strh, whereas skyemu gets 0xB68
[pcstoragetst.zip](https://github.com/user-attachments/files/15746332/pcstoragetst.zip)
image of results on hw:
![image](https://github.com/skylersaleh/SkyEmu/assets/102590697/cebbf439-659f-4f5d-80fc-8e5031912dd1)

**Comment by skylersaleh** [comment]
Half word stores to PC... thats horrible! Thanks for reporting this, I just submitted a fix and now match your results from HW. 

<img width="652" alt="image" src="https://github.com/skylersaleh/SkyEmu/assets/7118296/eb28360e-3854-4fda-b9c7-be14d0126619">
