### ISSUE TITLE
Trying to bind Capture/restore State to a controller crashes the emulator

### ISSUE THREAD

**Issue by negativeiqtest** [skylersaleh/SkyEmu#463]
As far as I've tried, both the web version and the Windows executable crash when I try to bind any of the capture/restore states to any button on my controller. The windows executable also refuses to open now and I don't know where the configs are saved lol

EDIT: If a game is loaded, you can rebind the buttons no problem. If no game is loaded, it crashes the emulator and fucks your config

**Comment by skylersaleh** [comment]
Does this occur on the latest nightly builds? 

https://github.com/skylersaleh/SkyEmu/pull/321

**Comment by negativeiqtest** [comment]
Dev branch works fine
