### ISSUE TITLE
(Homebrew) Sushi the Cat - Audio Problem

### ISSUE THREAD

**Issue by RenanSD007** [skylersaleh/SkyEmu#474]
This game has a lot of noise in the audio, there is a little less in the web version (master branch), but it should be like this (VBA-M RetroArch)

SkyEmu (Dev)
https://cdn.discordapp.com/attachments/883725953673617463/1273768969467072536/2024_08_15_19_20_23.mp4?ex=66bfd14b&is=66be7fcb&hm=c2e91c650e547562c86276636539adc86f34dbad6495ab76c25a12d1288e829c&

Webapp (Master)
https://cdn.discordapp.com/attachments/883725953673617463/1273776116426866728/2024_08_15_19_49_40.mp4?ex=66bfd7f3&is=66be8673&hm=e7e0131ca6e44864eacf3e642f6e738de5b79a7a84fff08ecd4b2077b83bc496&

VBA-M
https://cdn.discordapp.com/attachments/883725953673617463/1273779534205816894/2024_08_15_19_59_11.mp4?ex=66bfdb22&is=66be89a2&hm=30c8193bb4364033e3a13623dc94f84fc353b0fdc05f5a43593b04fbc2e6a821&

**Comment by skylersaleh** [comment]
This issue seems to also exist in Magical Vacation.

From debugging it, it looks like data is not getting put in memory before the DMA copies it over to the audio FIFO
