### ISSUE TITLE
Malformed background on GBC game

### ISSUE THREAD

**Issue by iWiggins** [skylersaleh/SkyEmu#5]
The background of the GameBoy Color game SpongeBob Squarepants - Legend of the Lost Spatula is incorrectly mapped:

![Screenshot](https://user-images.githubusercontent.com/7118298/133891513-eba2a72a-9e70-440f-bf85-bda466a5a4fc.PNG)

To replicate:

- Start the SkyBoy emulator using the github.io link, https://skylersaleh.github.io/SkyBoy/.
- Open the game "SpongeBob Squarepants - Legend of the Lost Spatula"
- Start a new game

**Comment by skylersaleh** [comment]
This is fixed in the latest master. 
<img width="912" alt="image" src="https://user-images.githubusercontent.com/7118296/171577213-ca2cbfc4-cb2c-473a-8b87-815444311fc9.png">
