### ISSUE TITLE
Need for speed flickering graphics on title menu

### ISSUE THREAD

**Issue by jmc92** [skylersaleh/SkyEmu#53]
There's about 3-5 pixels in a long strip at the bottom of the menu  on Need for Speed - Porsche Unleashed that keeps flickering, on the screen where you have all the options after pressing start.

This persists, even while using the official bios.

**Comment by fleroviux** [comment]
This actually happens on original hardware too:

https://user-images.githubusercontent.com/13669774/179040029-0014ff90-0db5-4926-92c8-a78d1a8b4dea.mp4

.

**Comment by skylersaleh** [comment]
Thanks guys for reporting and triaging this 👍 

I'll close this since it occurs on HW.
