### ISSUE TITLE
ATV Quad Power Racing unplayable.

### ISSUE THREAD

**Issue by jmc92** [skylersaleh/SkyEmu#55]
Severe graphic corruption on the initial map. (Haven't checked other maps)
![sky emu atv quad power racing](https://user-images.githubusercontent.com/23234604/178944172-8f80074a-d548-41d2-8bc5-ee6e8d29be2d.jpg)

This persists, even while using the official bios.

**Comment by skylersaleh** [comment]
I have a fix I am pushing to https://github.com/skylersaleh/SkyEmu/pull/40 for this. 

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/7118296/180391237-6826570c-e767-4bb3-a9d3-4da9f760b60b.png">
