### ISSUE TITLE
Zen - Intergalactic Ninja (USA) graphics glitch

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#58]
![SkyEmu 14_07_2022 5_23_04 PM](https://user-images.githubusercontent.com/2696404/178949787-60e0cf52-e7e5-4ee4-85ac-855f8a4dc97e.png)

**Comment by skylersaleh** [comment]
<img width="1392" alt="Screen Shot 2022-09-18 at 1 08 42 PM" src="https://user-images.githubusercontent.com/7118296/190926583-dc760fb1-2d21-4604-a2a6-3f0fd071af66.png">
