### ISSUE TITLE
Scooby doo classic creep capers minor graphics glitch.

### ISSUE THREAD

**Issue by jmc92** [skylersaleh/SkyEmu#60]
Dr Jekyll's head keeps flickering in visibility.
![sky emu scooby](https://user-images.githubusercontent.com/23234604/178958232-8d29efcc-818b-4dc3-a841-ce9dba997d14.jpg)

Updated correct screenshot. Other emulators have this too, might be glitched on hardware as well.
This persists, even while using the official bios.

**Comment by skylersaleh** [comment]
Adding the help wanted tag here. Is there someone who can verify whether this bug occurs on HW?

**Comment by jmc92** [comment]
> Adding the help wanted tag here. Is there someone who can verify whether this bug occurs on HW?

There is a chance I can do so next week if I remember. My cartridge of this game resides with family members now.

**Comment by benderscruffy** [comment]
it happens on hardware aswell
not a bug

**Comment by skylersaleh** [comment]
Thanks @benderscruffy for testing this out. I'll close this issue.
