### ISSUE TITLE
Various Memory Leaks

### ISSUE THREAD

**Issue by CasualPokePlayer** [skylersaleh/SkyEmu#65]
I left SkyEmu running in the background and left my laptop unattended for around 9 or so hours, and go back to it and see SkyEmu has crashed (generic 0xc0000005 exception). Not only that, but other applications seem to have crashed, like Firefox and HexChat.

Looking at the Event Viewer shows warnings on low virtual memory, with SkyEmu taking a wooping 43282735104 bytes of memory, which seems to indicate a memory leak someplace (and would explain why other applications crashed, they probably didn't like running out of memory).

**Comment by CasualPokePlayer** [comment]
A runthrough with valgrind shows multiple memory leaks. se_load_recent_games_list (main.c:465) leaks memory as an example (calls se_get_pref_path which calls SDL_GetPrefPath which returns a heap allocated string, which is supposed to be freed by SDL_free, but isn't here). Of course this extends to anything using se_get_pref_path anyways. There's also a memory leak in frame (main.c:2450) as ImFontConfig_ImFontConfig() is called, and that returns a pointer to a heap allocated instance, which frame proceeds to dereference to copy to an instance on the stack and discards the pointer, leaking memory.

There's probably much more, those are just some I see running valgrind for a couple seconds.

**Comment by skylersaleh** [comment]
Thanks for finding these. I fixed those two you identified in a commit I just pushed to dev. I'll do some more triaging to identify memory leaks before 1.5 as well.

**Comment by skylersaleh** [comment]
Closing this for now, as I had some time to do a more thorough look for leaks and haven't found anymore. Please reopen or file a new issue if you find some more leaks. 

Thanks!
