### ISSUE TITLE
Fli-Plasma (PD) [C] glitchy line at top of screen

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#70]
![SkyEmu 17_07_2022 8_53_57 AM](https://user-images.githubusercontent.com/2696404/179379533-b4fe9e17-8015-4404-a694-2820ea857abb.png)

**Comment by skylersaleh** [comment]
Fixed in dev: https://github.com/skylersaleh/SkyEmu/pull/40

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/7118296/190931744-37b53bd8-8ddd-4f73-9e1c-bc6f216fbf93.png">
