### ISSUE TITLE
[Feature Request] Screen Rotation

### ISSUE THREAD

**Issue by benderscruffy** [skylersaleh/SkyEmu#74]
for games like BulletGBA
![SkyEmu 22_07_2022 5_09_42 PM](https://user-images.githubusercontent.com/2696404/180406034-a5c4f315-9e22-4cf7-b833-02fbd0045a9f.png)

**Comment by skylersaleh** [comment]
I have recently pushed functionality for implementing a bunch of new display options, including screen rotation to dev.
