### ISSUE TITLE
Golden Sun don't save

### ISSUE THREAD

**Issue by antoniomaurilio** [skylersaleh/SkyEmu#77]
Congratulations for the work....I tried several games and was successful in almost all of them. Only Golden sun had a bug...it doesn't save or read .sav

**Comment by skylersaleh** [comment]
This is related to this bug: https://github.com/skylersaleh/SkyEmu/issues/26

It got fixed in the development branch and is pending release in SkyEmu 1.5: https://github.com/skylersaleh/SkyEmu/pull/40
