### ISSUE TITLE
[Feature Request] Make the Default Controls more realistic

### ISSUE THREAD

**Issue by ghost** [skylersaleh/SkyEmu#83]
It would be wonderful if the default controls for onscreen touch screen controller could represent the original controls and position of the real Game Boy Advance. It is also possible to select other designs like original controls and position of the Game Boy Advance SP.

**Comment by skylersaleh** [comment]
Would it be possible for for you to draw a picture of what you have in mind?

**Comment by Pedlarplastic** [comment]
> Would it be possible for for you to draw a picture of what you have in mind?

Here is a picture.

![SP](https://user-images.githubusercontent.com/111258387/185184980-54d4aa22-61d2-4016-888e-56f62cc942c4.jpg)


For now it should be enough if SkyEmu integrates the button design.

Ideally, it would be possible to display a complete original Game Boy Advance SP in SkyEmu. For example, when connected to an iPad Pro 12.9 inches with a Nintendo Switch Pro controller and press the button on the Nintendo Switch Pro controller. The Game Boy Advance SP in SkyEmu has been brought to life.


Here are the buttons that can be used on a real Game Boy Advance SP with your fingers.

1x A button
1x B button
1x R button
1x L button
1x Start button
1x Select button
1x D-pad
1x Power switch
1x Brightness button
1x Volume slider

**Comment by skylersaleh** [comment]
Ah, so you are thinking of something like this feature in retro arch, except with a GBA SP? https://www.libretro.com/index.php/retroarch-introducing-the-mega-bezel/ ?

**Comment by Pedlarplastic** [comment]
> Ah, so you are thinking of something like this feature in retro arch, except with a GBA SP? https://www.libretro.com/index.php/retroarch-introducing-the-mega-bezel/ ?

I read through the post and tested this for a few minutes. It is partially well done, but it lacks a reality mode, currently it is more a custom mode. For example, the possibility to dynamically view the back of the device is missing, or when a button is clicked on a real controller, the buttons movement should also be simulated in emulator.
The possibility to activate only the reality mode (dynamic), that is original display resolution, original GBA SP, eventual and random LCD problems, GBA SP game can be inserted into the slot, use the volume slider and power switcher and everything else that was experienced with a real device.

Additionally should also include all the GBA SP models design that Nintendo has ever released.

It would be very nice if something like this can be experienced in SkyEmu.

**Comment by nenge123** [comment]
skin can see delta-skins repo

**Comment by nenge123** [comment]
@Pedlarplastic 
see here,that it is you want?
using a skin
>>[https://skyemu.nenge.net/]
>>[https://github.com/nenge123/skyemu-test]

**Comment by Pedlarplastic** [comment]
> @Pedlarplastic see here,that it is you want?using mobile to visit using a skin
> 
> > > [https://skyemu.nenge.net/]
> > > [https://github.com/nenge123/skyemu-test]

For the beginning it's ok, it's obvious that it was made by Fan, that's why the Delta symbol on some skins.

The ideal is to take the original hardware design of the original GBA SP and virtualize it.

**Comment by nenge123** [comment]
> For the beginning it's ok, it's obvious that it was made by Fan, that's why the Delta symbol on some skins.
> 
> The ideal is to take the original hardware design of the original GBA SP and virtualize it.


you can like the retroarch ,set a option file  to load skin . in the web vision load file on FS

**Comment by nenge123** [comment]
design look like of the original GBA SP

not to same it, because it's not good of NINTENDO

**Comment by skylersaleh** [comment]
This should be possible now with the theme engine in V4.
