### ISSUE TITLE
Pokemon - Blue Version (USA, Europe) (SGB Enhanced): music not fading properly

### ISSUE THREAD

**Issue by crebwyllion** [skylersaleh/SkyEmu#94]
Playing using the dev branch on Chromium for Android using GrapheneOS. When playing Pokémon Blue, music is supposed to (cross?)fade when switching areas that have different music (like Pallet Town to Route 1), but this is currently not happening.

**Comment by skylersaleh** [comment]
Thanks for reporting the bug! This should now be fixed in the dev branch.
